// Servio Operational Mock Data (Africa/Nairobi & KES Currency Standard)

import {
  Tenant,
  Room,
  Reservation,
  Guest,
  MenuItem,
  PosOrder,
  KdsTicket,
  InventoryItem,
  Recipe,
  Supplier,
  PurchaseOrder,
  GuestFolio,
  Payment,
  Expense,
  AuditLogItem,
} from './types';

export const INITIAL_HOTELIERS: Tenant[] = [
  {
    id: 'hot-01',
    tenant_code: 'TNT-NBO-01',
    hotel_name: 'Servio Hotel & Resort',
    legal_name: 'Servio Hospitality Kenya Ltd',
    slug: 'servio-nairobi',
    email: 'robert@servio.ke',
    phone: '+254 711 000 111',
    website: 'https://servionairobi.co.ke',
    address: '14 Riverside Drive, Westlands',
    city: 'Nairobi',
    county: 'Nairobi County',
    country: 'Kenya',
    timezone: 'Africa/Nairobi',
    currency: 'KES',
    logo_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=150&auto=format&fit=crop&q=80',
    primary_color: '#059669',
    secondary_color: '#1e293b',
    subscription_plan: 'PRO',
    subscription_status: 'ACTIVE',
    account_status: 'ACTIVE',
    rooms_count: 45,
    monthly_fee: 35000,
    created_at: '2025-01-15T08:00:00Z',
    updated_at: '2026-09-01T10:30:00Z',
  },
  {
    id: 'hot-02',
    tenant_code: 'TNT-MBA-02',
    hotel_name: 'Ocean Breeze Beach Resort',
    legal_name: 'Ocean Breeze Hospitality Group Ltd',
    slug: 'ocean-breeze-mombasa',
    email: 'fatuma@oceanbreeze.co.ke',
    phone: '+254 722 333 444',
    website: 'https://oceanbreeze.co.ke',
    address: 'Bamburi Beach Road',
    city: 'Mombasa',
    county: 'Mombasa County',
    country: 'Kenya',
    timezone: 'Africa/Nairobi',
    currency: 'KES',
    logo_url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=150&auto=format&fit=crop&q=80',
    primary_color: '#0284c7',
    secondary_color: '#0f172a',
    subscription_plan: 'ENTERPRISE',
    subscription_status: 'ACTIVE',
    account_status: 'ACTIVE',
    rooms_count: 120,
    monthly_fee: 85000,
    created_at: '2025-03-10T09:15:00Z',
    updated_at: '2026-08-20T14:10:00Z',
  },
  {
    id: 'hot-03',
    tenant_code: 'TNT-NVS-03',
    hotel_name: 'Savannah Safari Lodge',
    legal_name: 'Savannah Eco Tourism Ltd',
    slug: 'savannah-naivasha',
    email: 'jkariuki@savannahlodge.ke',
    phone: '+254 733 555 666',
    website: 'https://savannahlodge.ke',
    address: 'Moi South Lake Road',
    city: 'Naivasha',
    county: 'Nakuru County',
    country: 'Kenya',
    timezone: 'Africa/Nairobi',
    currency: 'KES',
    logo_url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=150&auto=format&fit=crop&q=80',
    primary_color: '#d97706',
    secondary_color: '#27272a',
    subscription_plan: 'PRO',
    subscription_status: 'ACTIVE',
    account_status: 'ACTIVE',
    rooms_count: 30,
    monthly_fee: 35000,
    created_at: '2025-06-01T11:00:00Z',
    updated_at: '2026-07-15T16:20:00Z',
  },
  {
    id: 'hot-04',
    tenant_code: 'TNT-NKR-04',
    hotel_name: 'Grand Peak Hotel',
    legal_name: 'Rift Valley Heights Ltd',
    slug: 'grand-peak-nakuru',
    email: 'info@grandpeaknakuru.com',
    phone: '+254 700 888 999',
    website: 'https://grandpeaknakuru.com',
    address: 'Kenyatta Avenue',
    city: 'Nakuru',
    county: 'Nakuru County',
    country: 'Kenya',
    timezone: 'Africa/Nairobi',
    currency: 'KES',
    logo_url: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=150&auto=format&fit=crop&q=80',
    primary_color: '#dc2626',
    secondary_color: '#18181b',
    subscription_plan: 'BASIC',
    subscription_status: 'PAST_DUE',
    account_status: 'SUSPENDED',
    rooms_count: 18,
    monthly_fee: 15000,
    created_at: '2025-08-20T14:30:00Z',
    updated_at: '2026-09-01T09:00:00Z',
    suspended_at: '2026-09-05T12:00:00Z',
  },
];

export const INITIAL_ROOMS: Room[] = [
  { id: 'rm-101', tenant_id: 'hot-01', roomNumber: '101', roomTypeId: 'rt-std', roomTypeName: 'Standard Room', floor: 1, status: 'CLEAN', occupancyStatus: 'OCCUPIED', currentGuestName: 'Amina Mohamed', currentReservationId: 'res-1001', nightlyRate: 8500 },
  { id: 'rm-102', tenant_id: 'hot-01', roomNumber: '102', roomTypeId: 'rt-std', roomTypeName: 'Standard Room', floor: 1, status: 'CLEAN', occupancyStatus: 'VACANT', nightlyRate: 8500 },
  { id: 'rm-103', tenant_id: 'hot-01', roomNumber: '103', roomTypeId: 'rt-std', roomTypeName: 'Standard Room', floor: 1, status: 'DIRTY', occupancyStatus: 'VACANT', assignedHousekeeper: 'Mary Wanjiku', nightlyRate: 8500 },
  { id: 'rm-104', tenant_id: 'hot-01', roomNumber: '104', roomTypeId: 'rt-std', roomTypeName: 'Standard Room', floor: 1, status: 'INSPECTED', occupancyStatus: 'VACANT', nightlyRate: 8500 },
  { id: 'rm-201', tenant_id: 'hot-01', roomNumber: '201', roomTypeId: 'rt-dlx', roomTypeName: 'Deluxe Suite', floor: 2, status: 'CLEAN', occupancyStatus: 'OCCUPIED', currentGuestName: 'David Ochieng', currentReservationId: 'res-1002', nightlyRate: 14500 },
  { id: 'rm-202', tenant_id: 'hot-01', roomNumber: '202', roomTypeId: 'rt-dlx', roomTypeName: 'Deluxe Suite', floor: 2, status: 'CLEAN', occupancyStatus: 'VACANT', nightlyRate: 14500 },
  { id: 'rm-203', tenant_id: 'hot-01', roomNumber: '203', roomTypeId: 'rt-dlx', roomTypeName: 'Deluxe Suite', floor: 2, status: 'DIRTY', occupancyStatus: 'VACANT', assignedHousekeeper: 'John Kiprop', nightlyRate: 14500 },
  { id: 'rm-204', tenant_id: 'hot-01', roomNumber: '204', roomTypeId: 'rt-dlx', roomTypeName: 'Deluxe Suite', floor: 2, status: 'CLEAN', occupancyStatus: 'OCCUPIED', currentGuestName: 'John Kamau', currentReservationId: 'res-1003', nightlyRate: 14500 },
  { id: 'rm-301', tenant_id: 'hot-01', roomNumber: '301', roomTypeId: 'rt-exe', roomTypeName: 'Executive Ocean View', floor: 3, status: 'CLEAN', occupancyStatus: 'OCCUPIED', currentGuestName: 'Sarah Jenkins', currentReservationId: 'res-1004', nightlyRate: 22000 },
  { id: 'rm-302', tenant_id: 'hot-01', roomNumber: '302', roomTypeId: 'rt-exe', roomTypeName: 'Executive Ocean View', floor: 3, status: 'INSPECTED', occupancyStatus: 'VACANT', nightlyRate: 22000 },
  { id: 'rm-303', tenant_id: 'hot-01', roomNumber: '303', roomTypeId: 'rt-prs', roomTypeName: 'Presidential Suite', floor: 3, status: 'CLEAN', occupancyStatus: 'VACANT', nightlyRate: 45000 },
  { id: 'rm-304', tenant_id: 'hot-01', roomNumber: '304', roomTypeId: 'rt-exe', roomTypeName: 'Executive Ocean View', floor: 3, status: 'OUT_OF_SERVICE', occupancyStatus: 'VACANT', nightlyRate: 22000 },
];

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: 'res-1001',
    tenant_id: 'hot-01',
    reservationNumber: 'RSV-2026-0811',
    guestId: 'gst-01',
    guestName: 'Amina Mohamed',
    guestEmail: 'amina.mohamed@example.ke',
    guestPhone: '+254 722 123456',
    roomId: 'rm-101',
    roomNumber: '101',
    roomTypeName: 'Standard Room',
    checkInDate: '2026-09-14',
    checkOutDate: '2026-09-18',
    status: 'CHECKED_IN',
    adultsCount: 2,
    childrenCount: 0,
    totalAmount: 34000,
    depositPaid: 17000,
    specialRequests: 'High floor, late arrival',
    folioId: 'fol-1001',
  },
  {
    id: 'res-1002',
    tenant_id: 'hot-01',
    reservationNumber: 'RSV-2026-0812',
    guestId: 'gst-02',
    guestName: 'David Ochieng',
    guestEmail: 'david.ochieng@example.ke',
    guestPhone: '+254 733 987654',
    roomId: 'rm-201',
    roomNumber: '201',
    roomTypeName: 'Deluxe Suite',
    checkInDate: '2026-09-15',
    checkOutDate: '2026-09-19',
    status: 'CHECKED_IN',
    adultsCount: 1,
    childrenCount: 1,
    totalAmount: 58000,
    depositPaid: 58000,
    specialRequests: 'Extra towels and crib required',
    folioId: 'fol-1002',
  },
  {
    id: 'res-1003',
    reservationNumber: 'RSV-2026-0813',
    guestId: 'gst-03',
    guestName: 'John Kamau',
    guestEmail: 'john.kamau@business.co.ke',
    guestPhone: '+254 711 456789',
    roomId: 'rm-204',
    roomNumber: '204',
    roomTypeName: 'Deluxe Suite',
    checkInDate: '2026-09-15',
    checkOutDate: '2026-09-17',
    status: 'CHECKED_IN',
    adultsCount: 1,
    childrenCount: 0,
    totalAmount: 29000,
    depositPaid: 15000,
    specialRequests: 'Airport transfer needed',
    folioId: 'fol-1003',
  },
  {
    id: 'res-1004',
    reservationNumber: 'RSV-2026-0814',
    guestId: 'gst-04',
    guestName: 'Sarah Jenkins',
    guestEmail: 'sarah.j@safaritravel.com',
    guestPhone: '+44 7911 123456',
    roomId: 'rm-301',
    roomNumber: '301',
    roomTypeName: 'Executive Ocean View',
    checkInDate: '2026-09-16',
    checkOutDate: '2026-09-21',
    status: 'CHECKED_IN',
    adultsCount: 2,
    childrenCount: 0,
    totalAmount: 110000,
    depositPaid: 50000,
    specialRequests: 'Honeymoon arrangement, sparkling wine',
    folioId: 'fol-1004',
  },
  {
    id: 'res-1005',
    reservationNumber: 'RSV-2026-0815',
    guestId: 'gst-05',
    guestName: 'Dr. Hassan Mwangi',
    guestEmail: 'hassan@mwangiclinic.or.ke',
    guestPhone: '+254 720 998877',
    roomId: 'rm-302',
    roomNumber: '302',
    roomTypeName: 'Executive Ocean View',
    checkInDate: '2026-09-17',
    checkOutDate: '2026-09-20',
    status: 'CONFIRMED',
    adultsCount: 2,
    childrenCount: 0,
    totalAmount: 66000,
    depositPaid: 33000,
    specialRequests: 'Quiet room away from elevator',
    folioId: 'fol-1005',
  },
];

export const INITIAL_GUESTS: Guest[] = [
  {
    id: 'gst-01',
    firstName: 'Amina',
    lastName: 'Mohamed',
    email: 'amina.mohamed@example.ke',
    phone: '+254 722 123456',
    idType: 'NATIONAL_ID',
    idNumber: '28471902',
    nationality: 'Kenyan',
    isVip: true,
    totalStays: 4,
    totalSpent: 184000,
    notes: 'Prefers quiet corner room, almond milk for breakfast',
    documentsCount: 2,
  },
  {
    id: 'gst-02',
    firstName: 'David',
    lastName: 'Ochieng',
    email: 'david.ochieng@example.ke',
    phone: '+254 733 987654',
    idType: 'NATIONAL_ID',
    idNumber: '19482019',
    nationality: 'Kenyan',
    isVip: false,
    totalStays: 2,
    totalSpent: 96000,
    notes: 'Corporate rate account - TechHub Kenya',
    documentsCount: 1,
  },
  {
    id: 'gst-03',
    firstName: 'John',
    lastName: 'Kamau',
    email: 'john.kamau@business.co.ke',
    phone: '+254 711 456789',
    idType: 'NATIONAL_ID',
    idNumber: '31092817',
    nationality: 'Kenyan',
    isVip: false,
    totalStays: 1,
    totalSpent: 29000,
    notes: 'Express checkout requested',
    documentsCount: 1,
  },
  {
    id: 'gst-04',
    firstName: 'Sarah',
    lastName: 'Jenkins',
    email: 'sarah.j@safaritravel.com',
    phone: '+44 7911 123456',
    idType: 'PASSPORT',
    idNumber: 'GB908212C',
    nationality: 'British',
    isVip: true,
    totalStays: 3,
    totalSpent: 310000,
    notes: 'VIP Guest, Safari group organizer',
    documentsCount: 2,
  },
  {
    id: 'gst-05',
    firstName: 'Hassan',
    lastName: 'Mwangi',
    email: 'hassan@mwangiclinic.or.ke',
    phone: '+254 720 998877',
    idType: 'NATIONAL_ID',
    idNumber: '24910283',
    nationality: 'Kenyan',
    isVip: false,
    totalStays: 5,
    totalSpent: 220000,
    notes: 'Late arrival expected at 10 PM',
    documentsCount: 1,
  },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  {
    id: 'menu-01',
    categoryId: 'cat-mains',
    categoryName: 'Main Courses',
    code: 'MC-01',
    name: 'Swahili Seafood Platter',
    description: 'Fresh grilled prawns, calamari, red snapper fillet with coconut rice and kachumbari',
    price: 2800,
    taxRate: 16,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=500&auto=format&fit=crop',
    modifiers: [
      {
        groupName: 'Choice of Starch',
        options: [
          { id: 'mod-101', name: 'Coconut Rice', price: 0 },
          { id: 'mod-102', name: 'Potato Chips', price: 150 },
          { id: 'mod-103', name: 'Ugali', price: 0 },
        ],
      },
    ],
  },
  {
    id: 'menu-02',
    categoryId: 'cat-mains',
    categoryName: 'Main Courses',
    code: 'MC-02',
    name: 'Nyama Choma Combo',
    description: 'Slow roasted prime beef sirloin and goat ribs served with ugali, sukuma wiki & kachumbari',
    price: 2200,
    taxRate: 16,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop',
    modifiers: [
      {
        groupName: 'Meat Doneness',
        options: [
          { id: 'mod-201', name: 'Medium Well', price: 0 },
          { id: 'mod-202', name: 'Well Done', price: 0 },
        ],
      },
    ],
  },
  {
    id: 'menu-03',
    categoryId: 'cat-mains',
    categoryName: 'Main Courses',
    code: 'MC-03',
    name: 'Gourmet Servio Burger',
    description: '200g prime beef patty, melted cheddar, crispy bacon, caramelized onions on brioche bun',
    price: 1650,
    taxRate: 16,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop',
    variants: [
      { id: 'var-b1', name: 'Single Patty', priceModifier: 0 },
      { id: 'var-b2', name: 'Double Patty', priceModifier: 450 },
    ],
  },
  {
    id: 'menu-04',
    categoryId: 'cat-starters',
    categoryName: 'Starters & Sides',
    code: 'ST-01',
    name: 'Masala Chips',
    description: 'Crispy thick-cut fries tossed in spicy tomato masala gravy with coriander',
    price: 650,
    taxRate: 16,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=500&auto=format&fit=crop',
  },
  {
    id: 'menu-05',
    categoryId: 'cat-drinks',
    categoryName: 'Beverages & Bar',
    code: 'DR-01',
    name: 'Dawa Cocktail',
    description: 'Kenyan vodka, fresh lime juice, crushed ice, garnished with honey stick',
    price: 850,
    taxRate: 16,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=500&auto=format&fit=crop',
  },
  {
    id: 'menu-06',
    categoryId: 'cat-drinks',
    categoryName: 'Beverages & Bar',
    code: 'DR-02',
    name: 'Tusker Lager (500ml)',
    description: 'Classic cold Kenyan draft lager',
    price: 450,
    taxRate: 16,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=500&auto=format&fit=crop',
  },
  {
    id: 'menu-07',
    categoryId: 'cat-coffee',
    categoryName: 'Coffee & Breakfast',
    code: 'CF-01',
    name: 'Double Espresso / Cappuccino',
    description: 'Freshly brewed Arabica beans from Mt. Kenya region',
    price: 400,
    taxRate: 16,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1534778101976-62847782c213?w=500&auto=format&fit=crop',
  },
];

export const INITIAL_POS_ORDERS: PosOrder[] = [
  {
    id: 'ord-101',
    orderNumber: 'POS-2026-041',
    outletName: 'Main Restaurant',
    orderType: 'DINE_IN',
    tableNumber: 'Table 4',
    waiterName: 'Samuel Odhiambo',
    status: 'COMPLETED',
    items: [
      { id: 'item-1', menuItemId: 'menu-01', menuItemName: 'Swahili Seafood Platter', quantity: 1, unitPrice: 2800, totalPrice: 2800 },
      { id: 'item-2', menuItemId: 'menu-06', menuItemName: 'Tusker Lager (500ml)', quantity: 2, unitPrice: 450, totalPrice: 900 },
    ],
    subtotal: 3700,
    taxAmount: 592,
    discountAmount: 0,
    totalAmount: 3700,
    createdAt: '2026-09-16T12:30:00Z',
  },
  {
    id: 'ord-102',
    orderNumber: 'POS-2026-042',
    outletName: 'Room Service',
    orderType: 'ROOM_SERVICE',
    roomNumber: '204',
    guestFolioId: 'fol-1003',
    waiterName: 'Grace Mutua',
    status: 'SENT_TO_KITCHEN',
    items: [
      { id: 'item-3', menuItemId: 'menu-03', menuItemName: 'Gourmet Servio Burger', quantity: 2, unitPrice: 1650, totalPrice: 3300, selectedVariant: 'Single Patty' },
      { id: 'item-4', menuItemId: 'menu-04', menuItemName: 'Masala Chips', quantity: 1, unitPrice: 650, totalPrice: 650 },
      { id: 'item-5', menuItemId: 'menu-05', menuItemName: 'Dawa Cocktail', quantity: 2, unitPrice: 850, totalPrice: 1700 },
    ],
    subtotal: 5650,
    taxAmount: 904,
    discountAmount: 0,
    totalAmount: 5650,
    createdAt: '2026-09-16T13:10:00Z',
  },
];

export const INITIAL_KDS_TICKETS: KdsTicket[] = [
  {
    id: 'kds-01',
    ticketNumber: 'KDS-901',
    orderId: 'ord-102',
    orderNumber: 'POS-2026-042',
    orderType: 'ROOM_SERVICE',
    locationInfo: 'ROOM 204 (John Kamau)',
    stationName: 'Hot Grill Station',
    status: 'PREPARING',
    items: [
      { id: 'ki-1', name: 'Gourmet Servio Burger (Medium Well)', quantity: 2, notes: 'Extra cheddar, crisp bacon' },
      { id: 'ki-2', name: 'Masala Chips (Extra Spicy)', quantity: 1 },
    ],
    createdAt: '2026-09-16T13:10:00Z',
    elapsedMinutes: 12,
    priority: 'VIP',
  },
  {
    id: 'kds-02',
    ticketNumber: 'KDS-902',
    orderId: 'ord-103',
    orderNumber: 'POS-2026-043',
    orderType: 'DINE_IN',
    locationInfo: 'Table 8',
    stationName: 'Main Kitchen',
    status: 'NEW',
    items: [
      { id: 'ki-3', name: 'Nyama Choma Combo', quantity: 2, notes: 'Ugali & Sukuma Wiki' },
      { id: 'ki-4', name: 'Swahili Seafood Platter', quantity: 1 },
    ],
    createdAt: '2026-09-16T13:18:00Z',
    elapsedMinutes: 4,
    priority: 'NORMAL',
  },
  {
    id: 'kds-03',
    ticketNumber: 'KDS-899',
    orderId: 'ord-100',
    orderNumber: 'POS-2026-040',
    orderType: 'DINE_IN',
    locationInfo: 'Table 2',
    stationName: 'Bar Station',
    status: 'READY',
    items: [
      { id: 'ki-5', name: 'Dawa Cocktail', quantity: 3 },
      { id: 'ki-6', name: 'Fresh Passion Juice', quantity: 1 },
    ],
    createdAt: '2026-09-16T12:55:00Z',
    elapsedMinutes: 27,
    priority: 'NORMAL',
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  { id: 'inv-01', sku: 'SKU-MEAT-01', name: 'Prime Beef Sirloin', category: 'Meats & Poultry', uom: 'KG', currentStock: 48.5, minStock: 25.0, maxStock: 200.0, costPrice: 950, location: 'Kitchen Pantry', lastRestocked: '2026-09-14' },
  { id: 'inv-02', sku: 'SKU-SEAF-01', name: 'Jumbo Prawns & Snapper', category: 'Seafood', uom: 'KG', currentStock: 12.0, minStock: 15.0, maxStock: 80.0, costPrice: 1800, location: 'Kitchen Pantry', lastRestocked: '2026-09-12', expiryDate: '2026-09-20' },
  { id: 'inv-03', sku: 'SKU-VEG-01', name: 'Fresh Idaho Potatoes', category: 'Fresh Produce', uom: 'KG', currentStock: 140.0, minStock: 50.0, maxStock: 400.0, costPrice: 120, location: 'Main Store', lastRestocked: '2026-09-15' },
  { id: 'inv-04', sku: 'SKU-DAIR-01', name: 'Cheddar Cheese Blocks', category: 'Dairy', uom: 'KG', currentStock: 8.5, minStock: 10.0, maxStock: 50.0, costPrice: 1400, location: 'Kitchen Pantry', lastRestocked: '2026-09-10', expiryDate: '2026-10-15' },
  { id: 'inv-05', sku: 'SKU-BEV-01', name: 'Tusker Beer Crate (24)', category: 'Beverages', uom: 'PACK', currentStock: 18.0, minStock: 5.0, maxStock: 50.0, costPrice: 3800, location: 'Bar Store', lastRestocked: '2026-09-11' },
  { id: 'inv-06', sku: 'SKU-COFF-01', name: 'Mt. Kenya Arabica Beans', category: 'Beverages', uom: 'KG', currentStock: 15.0, minStock: 5.0, maxStock: 30.0, costPrice: 2100, location: 'Bar Store', lastRestocked: '2026-09-08' },
];

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: 'rec-01',
    menuItemId: 'menu-03',
    menuItemName: 'Gourmet Servio Burger',
    sellingPrice: 1650,
    ingredients: [
      { inventoryItemId: 'inv-01', inventoryItemName: 'Prime Beef Sirloin', quantityRequired: 0.22, uom: 'KG', costPerUnit: 950, totalCost: 209 },
      { inventoryItemId: 'inv-04', inventoryItemName: 'Cheddar Cheese Blocks', quantityRequired: 0.05, uom: 'KG', costPerUnit: 1400, totalCost: 70 },
      { inventoryItemId: 'inv-03', inventoryItemName: 'Fresh Idaho Potatoes', quantityRequired: 0.25, uom: 'KG', costPerUnit: 120, totalCost: 30 },
    ],
    totalIngredientCost: 309,
    foodCostPercentage: 18.7,
    grossMargin: 81.3,
  },
  {
    id: 'rec-02',
    menuItemId: 'menu-02',
    menuItemName: 'Nyama Choma Combo',
    sellingPrice: 2200,
    ingredients: [
      { inventoryItemId: 'inv-01', inventoryItemName: 'Prime Beef Sirloin', quantityRequired: 0.45, uom: 'KG', costPerUnit: 950, totalCost: 427.5 },
      { inventoryItemId: 'inv-03', inventoryItemName: 'Fresh Idaho Potatoes', quantityRequired: 0.20, uom: 'KG', costPerUnit: 120, totalCost: 24.0 },
    ],
    totalIngredientCost: 451.5,
    foodCostPercentage: 20.5,
    grossMargin: 79.5,
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  { id: 'sup-01', name: 'Highland Meats Kenya Ltd', contactPerson: 'Peter Kariuki', phone: '+254 722 889900', email: 'orders@highlandmeats.co.ke', taxId: 'P051283910A', categories: ['Meats & Poultry', 'Dairy'] },
  { id: 'sup-02', name: 'Mombasa Ocean Catch Co.', contactPerson: 'Fatuma Ali', phone: '+254 733 112233', email: 'sales@oceancatch.co.ke', taxId: 'P091823901C', categories: ['Seafood'] },
  { id: 'sup-03', name: 'Nairobi Beverage Distributors', contactPerson: 'James Omondi', phone: '+254 711 556677', email: 'supply@nairobibev.co.ke', taxId: 'P010293812B', categories: ['Beverages', 'Bar'] },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  { id: 'po-101', tenant_id: 'hot-01', poNumber: 'PO-2026-088', supplierId: 'sup-01', supplierName: 'Highland Meats Kenya Ltd', orderDate: '2026-09-14', expectedDelivery: '2026-09-17', status: 'SENT', totalAmount: 48500, items: [] },
  { id: 'po-102', tenant_id: 'hot-01', poNumber: 'PO-2026-089', supplierId: 'sup-03', supplierName: 'Nairobi Beverage Distributors', orderDate: '2026-09-10', expectedDelivery: '2026-09-12', status: 'DELIVERED', totalAmount: 76000, items: [] },
];

export const INITIAL_FOLIOS: GuestFolio[] = [
  {
    id: 'fol-1003',
    tenant_id: 'hot-01',
    folioNumber: 'FOL-2026-204',
    guestId: 'gst-1003',
    guestName: 'John Kamau',
    roomNumber: '204',
    reservationId: 'res-1003',
    status: 'OPEN',
    totalCharges: 34650,
    totalPayments: 15000,
    balance: 19650,
    items: [
      { id: 'fi-1', date: '2026-09-15', category: 'ROOM_CHARGE', description: 'Room Charge - Night 1 (Deluxe Suite 204)', amount: 14500 },
      { id: 'fi-2', date: '2026-09-15', category: 'TAX', description: 'VAT (16%) & Catering Levy (2%)', amount: 2610 },
      { id: 'fi-3', date: '2026-09-15', category: 'PAYMENT', description: 'M-Pesa Advance Deposit (Ref QK891238)', amount: -15000 },
      { id: 'fi-4', date: '2026-09-16', category: 'ROOM_CHARGE', description: 'Room Charge - Night 2 (Deluxe Suite 204)', amount: 14500 },
      { id: 'fi-5', date: '2026-09-16', category: 'RESTAURANT', description: 'Room Service Order #POS-2026-042', amount: 5650 },
      { id: 'fi-6', date: '2026-09-16', category: 'TAX', description: 'VAT (16%) & Catering Levy (2%)', amount: 2390 },
    ],
  },
  {
    id: 'fol-1001',
    tenant_id: 'hot-01',
    folioNumber: 'FOL-2026-101',
    guestId: 'gst-1001',
    guestName: 'Amina Mohamed',
    roomNumber: '101',
    reservationId: 'res-1001',
    status: 'OPEN',
    totalCharges: 40120,
    totalPayments: 17000,
    balance: 23120,
    items: [
      { id: 'fi-10', date: '2026-09-14', category: 'ROOM_CHARGE', description: 'Room Charge - Night 1', amount: 8500 },
      { id: 'fi-11', date: '2026-09-14', category: 'PAYMENT', description: 'Credit Card Deposit', amount: -17000 },
      { id: 'fi-12', date: '2026-09-15', category: 'ROOM_CHARGE', description: 'Room Charge - Night 2', amount: 8500 },
      { id: 'fi-13', date: '2026-09-16', category: 'ROOM_CHARGE', description: 'Room Charge - Night 3', amount: 8500 },
      { id: 'fi-14', date: '2026-09-16', category: 'LAUNDRY', description: 'Express Dry Cleaning Service', amount: 2400 },
    ],
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  { id: 'pay-01', tenant_id: 'hot-01', receiptNumber: 'RCT-2026-091', guestName: 'John Kamau', amount: 15000, method: 'MPESA', providerReference: 'QK891238', status: 'COMPLETED', timestamp: '2026-09-15T09:12:00Z' },
  { id: 'pay-02', tenant_id: 'hot-01', receiptNumber: 'RCT-2026-092', guestName: 'Amina Mohamed', amount: 17000, method: 'CARD', providerReference: 'TXN-9018239', status: 'COMPLETED', timestamp: '2026-09-14T14:20:00Z' },
  { id: 'pay-03', tenant_id: 'hot-01', receiptNumber: 'RCT-2026-093', orderId: 'ord-041', amount: 3700, method: 'CASH', status: 'COMPLETED', timestamp: '2026-09-16T12:45:00Z' },
];

export const INITIAL_EXPENSES: Expense[] = [
  { id: 'exp-01', tenant_id: 'hot-01', expenseNumber: 'EXP-101', category: 'UTILITIES', description: 'Kenya Power Commercial Electricity Bill', amount: 124500, expenseDate: '2026-09-10', approvedBy: 'GM - Robert' },
  { id: 'exp-02', tenant_id: 'hot-01', expenseNumber: 'EXP-102', category: 'FOOD_BEVERAGE', description: 'Guest Luxury Bathroom Amenities Restock', amount: 48000, expenseDate: '2026-09-12', approvedBy: 'Hotel Mgr - Alice' },
  { id: 'exp-03', tenant_id: 'hot-01', expenseNumber: 'EXP-103', category: 'MAINTENANCE', description: 'AC Chiller Compressor Servicing (Floor 3)', amount: 35000, expenseDate: '2026-09-14', approvedBy: 'GM - Robert' },
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  { id: 'aud-01', tenant_id: 'hot-01', timestamp: '2026-09-16T13:10:00Z', userName: 'Grace Mutua', userRole: 'WAITER', action: 'ROOM_SERVICE_CHARGE_POSTED', entity: 'GuestFolio', details: 'Posted Order #POS-2026-042 (5,650 KES) to Room 204 Folio', ipAddress: '192.168.1.102' },
  { id: 'aud-02', tenant_id: 'hot-01', timestamp: '2026-09-16T12:45:00Z', userName: 'Samuel Odhiambo', userRole: 'CASHIER', action: 'PAYMENT_RECEIVED', entity: 'Payment', details: 'Collected 3,700 KES Cash for Order #POS-2026-041', ipAddress: '192.168.1.105' },
  { id: 'aud-03', tenant_id: 'hot-01', timestamp: '2026-09-16T11:20:00Z', userName: 'Mary Wanjiku', userRole: 'RECEPTIONIST', action: 'GUEST_CHECK_IN', entity: 'Reservation', details: 'Checked in Sarah Jenkins to Executive Room 301', ipAddress: '192.168.1.100' },
  { id: 'aud-04', tenant_id: 'hot-01', timestamp: '2026-09-16T09:15:00Z', userName: 'John Kiprop', userRole: 'HOUSEKEEPER', action: 'ROOM_STATUS_UPDATED', entity: 'Room', details: 'Marked Room 204 CLEAN & INSPECTED', ipAddress: '192.168.1.110' },
];
